### ISSUE TITLE
Need ability to manage multiple projects in single server

### ISSUE THREAD

**Issue by yurii-voievodin** [jakeheis/VaporFlock#1]
Supervisor config file name vapor.conf hardcoded in "VaporSupervisord" class.
I tried to change this value to "Config.projectName" but it's doesn't helps (https://github.com/yura-voevodin/VaporFlock/commit/f072a45442cedf68f57779001f9b746ddb72a02a)

**How can we solve this?**

**Comment by jakeheis** [comment]
I definitely agree that there should be a Config option to override the default filename. While I'll certainly implement that when I get a chance, I'm surprised your commit did not fix the issue. The file path is computed as such:

```swift
public extension SupervisordProvider {
   
    var confFilePath: String {
        return "/etc/supervisor/conf.d/\(programName).conf"
    }
    
}
```
After updating the `FlockDependencies.json` of your project to point to this other repo and tag, did you successfully run `flock --clean-all && flock build`?
